server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
#spring:
#datasource:
#  type: com.zaxxer.hikari.HikariDataSource
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
#  username: root
#  password: yfy1410514150

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guigu-oa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: yfy1410514150
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8